# Generated by Django 4.1.2 on 2022-11-04 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "Categoryid",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Categoryname", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Prodid", models.CharField(max_length=7, unique=True)),
                ("Prodname", models.CharField(max_length=50)),
                ("Prodtype", models.CharField(max_length=30)),
                ("Price", models.IntegerField()),
                (
                    "Categoryid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ProdMgt.category",
                    ),
                ),
            ],
        ),
    ]
